name: test
on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: mihails-strasuns/setup-dlang@v1.1.1
          with:
            compiler: dmd-latest
        - name: Run tests
          run: dub test